version: '3.7'
networks:
  dev-network:
    driver: bridge
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - dev-network
volumes:
  mongodb_data_container: